apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: microservice-app-example
  name: redis-queue
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: microservice-app-example
        service: redis-queue
    spec:
      containers:
      - env:
        image: redis
        name: redis-queue
        ports:
        - containerPort: 6379
      restartPolicy: Always
